name: CI (Vitest)
# 🧪 Variante de CI para proyectos que usan Vitest en lugar de Jest

on:
  workflow_dispatch: {}
  # ▶️ Se ejecuta manualmente desde la pestaña Actions (Run workflow)

jobs:
  build-and-test-vitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    env:
      CI: true
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          # 💾 Cache de dependencias

      - name: 📦 Install dependencies (npm ci)
        run: npm ci

      - name: 🧠 Type check (TS)
        run: npm run type-check

      - name: 🔍 Lint (ESLint)
        run: npm run lint

      - name: 🧪 Run tests (Vitest)
        run: npm test -- --run

      - name: 🏗️ Build (Vite)
        run: npm run build

      - name: 📤 Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node-version }}
          path: dist

